import { TauntLine } from "./types";

export const TAUNT_LINES: TauntLine[] = [
  {
    id: "app-1",
    category: "appreciation",
    triggers: ["rolled_six", "released_token", "clutch_roll"],
    weight: 1,
    text_en: "Wah! dimaag laga diya 👏",
    text_hi: "Wah! dimaag laga diya 👏",
  },
  {
    id: "app-2",
    category: "appreciation",
    triggers: ["rolled_six", "clutch_roll"],
    weight: 1,
    text_en: "Kya move tha, maza aa gaya 🔥",
    text_hi: "Kya move tha, maza aa gaya 🔥",
  },
  {
    id: "app-3",
    category: "appreciation",
    triggers: ["released_token", "lead_change"],
    weight: 0.95,
    text_en: "Aaj toh form mein ho 😎",
    text_hi: "Aaj toh form mein ho 😎",
  },
  {
    id: "app-4",
    category: "appreciation",
    triggers: ["rolled_six", "captured"],
    weight: 0.95,
    text_en: "Solid khela boss 💪",
    text_hi: "Solid khela boss 💪",
  },
  {
    id: "app-5",
    category: "appreciation",
    triggers: ["clutch_roll", "near_win"],
    weight: 0.9,
    text_en: "Ye hui na baat 👑",
    text_hi: "Ye hui na baat 👑",
  },
  {
    id: "app-6",
    category: "appreciation",
    triggers: ["lead_change", "near_win"],
    weight: 0.9,
    text_en: "Aaj chamak rahe ho ✨",
    text_hi: "Aaj chamak rahe ho ✨",
  },
  {
    id: "app-7",
    category: "appreciation",
    triggers: ["clutch_roll", "lead_change"],
    weight: 0.85,
    text_en: "Pro nikle tum 🎯",
    text_hi: "Pro nikle tum 🎯",
  },
  {
    id: "taunt-1",
    category: "pressure",
    triggers: ["rolled_six", "lead_change", "near_win"],
    weight: 1,
    text_en: "Pakad sakta hai toh pakad 😜",
    text_hi: "Pakad sakta hai toh pakad 😜",
  },
  {
    id: "taunt-2",
    category: "pressure",
    triggers: ["lead_change", "blocked_opponent"],
    weight: 1,
    text_en: "Bas itna hi aata hai? 😏",
    text_hi: "Bas itna hi aata hai? 😏",
  },
  {
    id: "taunt-3",
    category: "pressure",
    triggers: ["blocked_opponent", "captured"],
    weight: 0.95,
    text_en: "Practice karke aana 😎",
    text_hi: "Practice karke aana 😎",
  },
  {
    id: "taunt-4",
    category: "pressure",
    triggers: ["lead_change", "last_place"],
    weight: 0.9,
    text_en: "Dheere khel raha hai bhai 😂",
    text_hi: "Dheere khel raha hai bhai 😂",
  },
  {
    id: "taunt-5",
    category: "dominance",
    triggers: ["near_win", "lead_change"],
    weight: 1,
    text_en: "Mujh tak pahunchna mushkil hai 💀",
    text_hi: "Mujh tak pahunchna mushkil hai 💀",
  },
  {
    id: "taunt-6",
    category: "dominance",
    triggers: ["lead_change", "captured"],
    weight: 0.95,
    text_en: "Ye level tumhare upar hai 😌",
    text_hi: "Ye level tumhare upar hai 😌",
  },
  {
    id: "taunt-7",
    category: "pressure",
    triggers: ["rolled_six", "clutch_roll"],
    weight: 0.9,
    text_en: "Thoda aur try kar lo 🤭",
    text_hi: "Thoda aur try kar lo 🤭",
  },
  {
    id: "taunt-8",
    category: "pressure",
    triggers: ["near_win", "clutch_roll", "captured"],
    weight: 1,
    text_en: "Pressure feel ho raha? 😈",
    text_hi: "Pressure feel ho raha? 😈",
  },
  {
    id: "rev-1",
    category: "revenge",
    triggers: ["revenge_kill", "captured"],
    weight: 1.1,
    text_en: "Ab aayega maza 😤",
    text_hi: "Ab aayega maza 😤",
  },
  {
    id: "rev-2",
    category: "revenge",
    triggers: ["revenge_kill", "captured"],
    weight: 1.1,
    text_en: "Badla pakka milega 😈",
    text_hi: "Badla pakka milega 😈",
  },
  {
    id: "rev-3",
    category: "revenge",
    triggers: ["revenge_kill", "captured"],
    weight: 1,
    text_en: "Ab meri entry dekh 🔥",
    text_hi: "Ab meri entry dekh 🔥",
  },
  {
    id: "rev-4",
    category: "revenge",
    triggers: ["revenge_kill", "last_place"],
    weight: 1,
    text_en: "Game palatne wala hoon 💀",
    text_hi: "Game palatne wala hoon 💀",
  },
  {
    id: "rev-5",
    category: "revenge",
    triggers: ["revenge_kill", "captured"],
    weight: 0.95,
    text_en: "Bach ke rehna ⚠️",
    text_hi: "Bach ke rehna ⚠️",
  },
  {
    id: "rev-6",
    category: "revenge",
    triggers: ["revenge_kill", "captured"],
    weight: 1,
    text_en: "Ab seedha nishana tum ho 🎯",
    text_hi: "Ab seedha nishana tum ho 🎯",
  },
  {
    id: "rev-7",
    category: "revenge",
    triggers: ["revenge_kill"],
    weight: 1.2,
    text_en: "Pichla yaad hai mujhe 😡",
    text_hi: "Pichla yaad hai mujhe 😡",
  },
  {
    id: "rev-8",
    category: "revenge",
    triggers: ["revenge_kill", "captured"],
    weight: 1.05,
    text_en: "Ab bhugto 😎",
    text_hi: "Ab bhugto 😎",
  },
  {
    id: "mind-1",
    category: "pressure",
    triggers: ["blocked_opponent", "near_win", "lead_change"],
    weight: 1,
    text_en: "Dar lag raha kya? 😈",
    text_hi: "Dar lag raha kya? 😈",
  },
  {
    id: "mind-2",
    category: "pressure",
    triggers: ["captured", "blocked_opponent"],
    weight: 0.95,
    text_en: "Haath kaanp rahe hain? 😂",
    text_hi: "Haath kaanp rahe hain? 😂",
  },
  {
    id: "mind-3",
    category: "clutch",
    triggers: ["clutch_roll", "near_win"],
    weight: 0.95,
    text_en: "Soch samajh ke chal 🧠",
    text_hi: "Soch samajh ke chal 🧠",
  },
  {
    id: "mind-4",
    category: "pressure",
    triggers: ["captured", "lead_change"],
    weight: 0.9,
    text_en: "Galti mat kar dena 😏",
    text_hi: "Galti mat kar dena 😏",
  },
  {
    id: "mind-5",
    category: "pressure",
    triggers: ["near_win", "blocked_opponent"],
    weight: 0.9,
    text_en: "Tum fasne wale ho 🤫",
    text_hi: "Tum fasne wale ho 🤫",
  },
  {
    id: "mind-6",
    category: "dominance",
    triggers: ["lead_change", "near_win"],
    weight: 0.9,
    text_en: "Bachna mushkil hai 😌",
    text_hi: "Bachna mushkil hai 😌",
  },
  {
    id: "mind-7",
    category: "pressure",
    triggers: ["captured", "near_win", "blocked_opponent"],
    weight: 0.9,
    text_en: "Nazar tum par hai 👀",
    text_hi: "Nazar tum par hai 👀",
  },
  {
    id: "esc-1",
    category: "mock_escape",
    triggers: ["narrow_escape", "entered_safe"],
    weight: 1.1,
    text_en: "Bach gaya main 😜",
    text_hi: "Bach gaya main 😜",
  },
  {
    id: "esc-2",
    category: "mock_escape",
    triggers: ["narrow_escape", "entered_safe"],
    weight: 1,
    text_en: "Phir miss kar diya 😂",
    text_hi: "Phir miss kar diya 😂",
  },
  {
    id: "esc-3",
    category: "mock_escape",
    triggers: ["entered_safe", "narrow_escape"],
    weight: 0.95,
    text_en: "Aaj nahi milega 😎",
    text_hi: "Aaj nahi milega 😎",
  },
  {
    id: "esc-4",
    category: "mock_escape",
    triggers: ["narrow_escape"],
    weight: 0.9,
    text_en: "Kismat kharab hai tumhari 🤭",
    text_hi: "Kismat kharab hai tumhari 🤭",
  },
  {
    id: "esc-5",
    category: "mock_escape",
    triggers: ["narrow_escape", "entered_safe"],
    weight: 1,
    text_en: "Itna paas aa ke bhi fail 😏",
    text_hi: "Itna paas aa ke bhi fail 😏",
  },
  {
    id: "esc-6",
    category: "mock_escape",
    triggers: ["entered_safe", "narrow_escape"],
    weight: 0.9,
    text_en: "Timing galat thi boss ⏰",
    text_hi: "Timing galat thi boss ⏰",
  },
  {
    id: "dom-1",
    category: "dominance",
    triggers: ["lead_change", "near_win", "captured"],
    weight: 1.1,
    text_en: "Ye mera area hai 👑",
    text_hi: "Ye mera area hai 👑",
  },
  {
    id: "dom-2",
    category: "dominance",
    triggers: ["lead_change", "blocked_opponent"],
    weight: 1,
    text_en: "Rule main karta hoon 😎",
    text_hi: "Rule main karta hoon 😎",
  },
  {
    id: "dom-3",
    category: "dominance",
    triggers: ["captured", "clutch_roll"],
    weight: 0.95,
    text_en: "Aaj sabko sikhaunga 🎯",
    text_hi: "Aaj sabko sikhaunga 🎯",
  },
  {
    id: "dom-4",
    category: "dominance",
    triggers: ["lead_change", "near_win"],
    weight: 0.95,
    text_en: "Topper ka game chal raha 🔥",
    text_hi: "Topper ka game chal raha 🔥",
  },
  {
    id: "dom-5",
    category: "dominance",
    triggers: ["lead_change", "near_win", "rolled_six"],
    weight: 0.95,
    text_en: "Mera din hai aaj 💪",
    text_hi: "Mera din hai aaj 💪",
  },
  {
    id: "dom-6",
    category: "dominance",
    triggers: ["near_win", "clutch_roll"],
    weight: 1,
    text_en: "Jeet fix samjho 😌",
    text_hi: "Jeet fix samjho 😌",
  },
  {
    id: "panic-1",
    category: "panic_reaction",
    triggers: ["got_captured"],
    weight: 1,
    text_en: "Arey yaar 😭",
    text_hi: "Arey yaar 😭",
  },
  {
    id: "panic-2",
    category: "panic_reaction",
    triggers: ["got_captured"],
    weight: 0.95,
    text_en: "Ye kya ho gaya 😵",
    text_hi: "Ye kya ho gaya 😵",
  },
  {
    id: "panic-3",
    category: "panic_reaction",
    triggers: ["got_captured", "last_place"],
    weight: 0.9,
    text_en: "Hadd hai bhai 😤",
    text_hi: "Hadd hai bhai 😤",
  },
  {
    id: "panic-4",
    category: "panic_reaction",
    triggers: ["got_captured", "last_place"],
    weight: 0.9,
    text_en: "Mera hi number kyun 😑",
    text_hi: "Mera hi number kyun 😑",
  },
  {
    id: "panic-5",
    category: "panic_reaction",
    triggers: ["got_captured", "last_place"],
    weight: 0.9,
    text_en: "Galat ho raha hai 😩",
    text_hi: "Galat ho raha hai 😩",
  },
  {
    id: "clutch-1",
    category: "clutch",
    triggers: ["near_win", "clutch_roll"],
    weight: 1.1,
    text_en: "Khatam tata bye bye 👋",
    text_hi: "Khatam tata bye bye 👋",
  },
  {
    id: "clutch-2",
    category: "clutch",
    triggers: ["near_win", "clutch_roll"],
    weight: 1,
    text_en: "Jeet gaya boss 😎",
    text_hi: "Jeet gaya boss 😎",
  },
  {
    id: "clutch-3",
    category: "clutch",
    triggers: ["near_win", "lead_change"],
    weight: 0.95,
    text_en: "Bola tha na 🔥",
    text_hi: "Bola tha na 🔥",
  },
  {
    id: "clutch-4",
    category: "clutch",
    triggers: ["near_win", "clutch_roll"],
    weight: 0.95,
    text_en: "Easy tha 😌",
    text_hi: "Easy tha 😌",
  },
  {
    id: "clutch-5",
    category: "clutch",
    triggers: ["near_win", "lead_change"],
    weight: 1,
    text_en: "King kaun? Main 👑",
    text_hi: "King kaun? Main 👑",
  },
  {
    id: "clutch-6",
    category: "clutch",
    triggers: ["near_win"],
    weight: 0.95,
    text_en: "Game over ho gaya 💀",
    text_hi: "Game over ho gaya 💀",
  },
];
